### ISSUE TITLE
細かいデザイン

### ISSUE THREAD

**Issue by sumiship** [tutorial-materials/roulette#5]
- 画面幅でデザインが崩れない様にする

**Comment by Kyosuke-Kaneko** [comment]
- フォントサイズ
- 背景の色
- ボタンの間隔
- 結果の内容

**Comment by Kyosuke-Kaneko** [comment]
間違えてmasterブランチで作業してimgディレクトリの構成を変更してしまったのですがお気になさらず
@sumiship 
```
/* user-select: none; */
```
って必要ですか？
>フォントサイズ
背景の色
ボタンの間隔
結果の内容

は別ブランチを一つ作って修正していきましょう！！
